#!/usr/bin/env bun

import { DEV_POSTGRES_PORT } from '@qafiyah/config';

const CORPUS_TABLES = [
  'collection_stats',
  'collections',
  'era_stats',
  'eras',
  'meter_stats',
  'meters',
  'poem_aliases',
  'poem_relations',
  'poem_type_stats',
  'poem_types',
  'poem_verses',
  'poems',
  'poet_aliases',
  'poet_stats',
  'poets',
  'rhyme_stats',
  'rhymes',
  'theme_stats',
  'themes',
  'verses',
] as const;

const OUTPUT = 'apps/api/generated/diesel/corpus.gen.rs';
const HEADER = '// Generated by `bun run db:schema` from the dev database. Do not edit.\n';

const password = process.env['POSTGRES_PASSWORD'] ?? 'qafiyah';
const database = process.env['POSTGRES_DB'] ?? 'qafiyah';
const url = `postgres://qafiyah:${password}@localhost:${DEV_POSTGRES_PORT}/${database}`;

const printed = Bun.spawnSync([
  'diesel',
  'print-schema',
  '--database-url',
  url,
  '-o',
  ...CORPUS_TABLES,
]);
if (printed.exitCode !== 0) {
  console.error(printed.stderr.toString());
  console.error(
    'needs `diesel` (cargo install diesel_cli --no-default-features --features postgres-bundled)'
  );
  process.exit(1);
}
const generated =
  HEADER +
  printed.stdout.toString().replace(/^\/\/ @generated automatically by Diesel CLI\.\n/u, '');

if (process.argv.includes('--check')) {
  const committed = await Bun.file(OUTPUT).text();
  if (committed !== generated) {
    console.error(`${OUTPUT} is stale: run bun run db:schema`);
    process.exit(1);
  }
  console.log(`${OUTPUT} matches the dev database`);
} else {
  await Bun.write(OUTPUT, generated);
  console.log(`wrote ${OUTPUT}`);
}
