#!/usr/bin/env bun

import { DEV_POSTGRES_PORT } from '@qafiyah/config';

const CORPUS_TABLES = [
  'collection_stats',
  'collections',
  'era_stats',
  'eras',
  'meter_stats',
  'meters',
  'poem_aliases',
  'poem_relations',
  'poem_type_stats',
  'poem_types',
  'poem_verses',
  'poems',
  'poet_aliases',
  'poet_stats',
  'poets',
  'rhyme_stats',
  'rhymes',
  'theme_stats',
  'themes',
  'verses',
] as const;

const ACCOUNTS_TABLES = [
  'api_keys',
  'identities',
  'plans',
  'sessions',
  'usage_hourly',
  'users',
] as const;

const HEADER = '// Generated by `bun run db:schema` from the dev database. Do not edit.\n';

const ownerPassword = process.env['POSTGRES_PASSWORD'] ?? 'qafiyah';
const accountsPassword = process.env['PG_ACCOUNTS_PASSWORD'] ?? 'qafiyah-dev-pg-accounts';
const database = process.env['POSTGRES_DB'] ?? 'qafiyah';

const SCHEMAS = [
  {
    output: 'apps/api/generated/diesel/corpus.gen.rs',
    url: `postgres://qafiyah:${ownerPassword}@localhost:${DEV_POSTGRES_PORT}/${database}`,
    tables: CORPUS_TABLES,
  },
  {
    output: 'apps/api/generated/diesel/accounts.gen.rs',
    url: `postgres://qafiyah_accounts:${accountsPassword}@localhost:${DEV_POSTGRES_PORT}/qafiyah_accounts`,
    tables: ACCOUNTS_TABLES,
  },
] as const;

let stale = false;
for (const { output, url, tables } of SCHEMAS) {
  const printed = Bun.spawnSync(['diesel', 'print-schema', '--database-url', url, '-o', ...tables]);
  if (printed.exitCode !== 0) {
    console.error(printed.stderr.toString());
    console.error(
      'needs `diesel` (cargo install diesel_cli --no-default-features --features postgres-bundled)'
    );
    process.exit(1);
  }
  const generated =
    HEADER +
    printed.stdout.toString().replace(/^\/\/ @generated automatically by Diesel CLI\.\n/u, '');
  if (process.argv.includes('--check')) {
    if ((await Bun.file(output).text()) !== generated) {
      console.error(`${output} is stale: run bun run db:schema`);
      stale = true;
    }
  } else {
    await Bun.write(output, generated);
    console.log(`wrote ${output}`);
  }
}
if (stale) process.exit(1);
if (process.argv.includes('--check')) console.log('the Diesel schemas match the dev databases');
