export const GENERATED_HEADER =
  '<!-- Generated by scripts/docs/diagrams.ts from docs/architecture/workspace.dsl. Do not edit. Run: bun run docs:diagrams -->';

const EXPORTED_VIEW = /^structurizr-([a-z0-9][a-z0-9-]*)\.svg$/;
const XML_DECLARATION = /^<\?xml[^>]*\?>/;

export function generatedName(exported: string): string | undefined {
  const match = EXPORTED_VIEW.exec(exported);
  return match === null ? undefined : `${match[1]}.gen.svg`;
}

export function withHeader(svg: string): string {
  const body = svg.trimEnd();
  const declaration = XML_DECLARATION.exec(body);
  if (declaration === null) return `${GENERATED_HEADER}\n${body}\n`;
  return `${declaration[0]}\n${GENERATED_HEADER}\n${body.slice(declaration[0].length)}\n`;
}

export function stale(existing: readonly string[], produced: readonly string[]): string[] {
  const kept = new Set(produced);
  return existing.filter((name) => !kept.has(name));
}
